var questions = [
    ["How are you doing (name)?", "(response)? This interests me."],
    ["(name), do you feel lonely?", "You can do better than (response)! I know you can."],
    ["Do you need anything (name)?", "Maybe we can get (response) together!"],
    ["I never get enough water. What should I do?", "(response)? Wow! You're smart!"],
    ["If you ever need anything I'm here", "Yes. Exactly."]
    ["I was thinking about you (name)! How have you been.", "(response) is always an interesting feeling."],
    ["If you could be anything what would you be?", "(response)s are cool but tulips are cooler!"],
    ["It's hard to go to sleep. Have you been sleeping well?", "I guess we're on the same page!"],
    ["Sometimes I look at the sky and wonder if it'll eat me.", "Well. It's always a fear!"],
    ["What scares you the most?", "(response)? I thought so."],
    ["What's something you like (name)?", "I think rain is better than (response)!"],
    ["Relationships are like flowers. If you don't water them, they'll die!", "Never heard that one!"],
    ["I hope our friendship lasts. Do you hope so too?", "Well we'll never know!"],
    ["Apples or oranges?", "I can't really decide!"],
    ["I think beds are comfier than chairs (name).", "Flower beds of course!"],
    ["Say anything! I'll wait.", "(response)! That's so you!"],
    ["How would you describe yourself?", "(response)? I think you're amazing!"],
    ["Remember to drink water (name)!", "No point in saving it!"],
    ["It gets stormy here all the time.", "I live in The Bahamas by the way."],
    ["Someday I hope I get to meet another tulip (name).", "I never thought of that!"],
    ["Did you know that moonlight is actually sunlight?", "Still get your sunlight though!"],
    ["Time is moving fast (name).", "I wouldn't say (response), but I am a tulip!"],
    ["Knock knock.", "Great to see you!"],
    ["Are you smart?", "Well I don't even know 2+2!"],
    ["(name), are you better than you were a year ago?", "(response)! I used to be just a seed!"],
    ["Are you living life to the fullest (name)?", "There's always more in life to explore!"],
    ["What was the last book you read (name)?", "I should check out (response) some time!"],
    ["What's bothering you?", "(response) would bother me too."],
    ["What made you smile today?", "I smiled from (response) too!"],
    ["What is your favorite podcast?", "Here in the plant world we don't seem to get (response)."],
    ["Cats or dogs? Why?", "I feel the same way."],
    ["I feel a spark here (name).", "You really are an interesting person!"],
    ["Water is to dirt as dirt is to?", "(response)? I thought you would say me!"],
    ["Except of looking sideways look up.", "Don't you start comparing yourself to me now!"],
    ["The world is a lot simpler than it looks (name).", "You make an interesting point. I wish more people would think like you!"],
    ["Be good (name).", "Always try your best!"],
    ["Give and take. That's what us plants do!", "You're like us too!"],
    ["People are good at the end of the day (name).", "(response). Is a generalization."],
    ["What subject are you good at?", "I have a friend who majored in (reponse)!"],
    ["I need to be cheered up.", "Thanks for the advice!"],
    ["What color goes with red?", "You weren't thinking of me weren't you!"],
    ["What did you eat today.", "(response) tastes great doesn't it!"],
    ["You're a good person (name). You know that?", "I think you are!"],
    ["It's hard being sad when you're outside all day.", "The world is pretty cool huh."],
    ["When I'm gone another tulip will take my place!", "It's the circle of life!"],
    ["Have you judged a book by its cover recently?", "It's good that you're aware!"],
    ["I bet you're wondering what my name is.", "I actually don't have one!"],
    ["(name), (name), (name). It has a nice ring to it!", "(response)? Don't be so humble!"],
    ["Have you had the chance to go outside today (name)?", "I would!"],
    ["Plants need their energy and so do (name)s.", "What does energize you?"],
    ["Life is a mix of nature and nurture.", "I guess we'd make a great team!"]
];