var questions = [
    ["How are you doing (name)?", "(response)? This interests me."],
    ["(name), do you feel lonely?", "You can do better than (response)! I know you can."],
    ["Do you need anything (name)?", "Maybe we can get (response) together!"],
    ["I never get enough water. What should I do?", "(response)? Wow! You're smart!"],
    ["If you ever need anything I'm here", "Yes. Exactly."]
    ["I was thinking about you (name)! How have you been.", "(response) is always an interesting feeling."],
    ["If you could be anything what would you be?", "(response)s are cool but tulips are cooler!"],
    ["It's hard to go to sleep. Have you been sleeping well?", "I guess we're on the same page!"],
    ["Sometimes I look at the sky and wonder if it'll eat me.", "Well. It's always a fear!"],
    ["What scares you the most?", "(response)? I thought so."],
    ["What's something you like (name)?", "I think rain is better than (response)!"],
    ["Relationships are like flowers. If you don't water them, they'll die!", "Never heard that one!"],
    ["I hope our friendship lasts. Do you hope so too?", "Well we'll never know!"],
    ["Apples or oranges?", "I can't really decide!"],
    ["I think beds are comfier than chairs (name).", "Flower beds of course!"],
    ["Say anything! I'll wait.", "(response)! That's so you!"],
    ["How would you describe yourself?", "(response)? I think you're amazing!"],
    ["Remember to drink water (name)!", "No point in saving it!"],
    ["It gets stormy here all the time.", "I live in The Bahamas by the way."],
    ["Someday I hope I get to meet another tulip (name).", "I never thought of that!"],
    ["Did you know that moonlight is actually sunlight?", "Still get your sunlight though!"],
    ["Time is moving fast (name).", "I wouldn't say (response), but I am a tulip!"],
    ["Knock knock.", "Great to see you!"],
    ["Are you smart?", "Well I don't even know 2+2!"],
    ["(name), are you better than you were a year ago?", "(response)! I used to be just a seed!"],
    ["Are you living life to the fullest (name)?", "There's always more in life to explore!"],
];